[api] add missing header to `api/oc_ri.c`
This fixes the build warning below

```
[363/530] Building C object CMakeFiles/kisClientServer.dir/api/oc_ri.c.obj
/Users/matran/repos/KNX-IOT-STACK-staging/api/oc_ri.c: In function 'oc_ri_get_query_value':
/Users/matran/repos/KNX-IOT-STACK-staging/api/oc_ri.c:481:30: warning: implicit declaration of function 'strncasecmp'; did you mean 'strncmp'? [-Wimplicit-function-declaration]
  481 |     if (kl == strlen(key) && strncasecmp(key, k, kl) == 0) {
      |                              ^~~~~~~~~~~
      |                              strncmp
```